import { Routes } from '@angular/router';
import { adminGuard } from './core/guards/admin.guard';

export const routes: Routes = [
	{ path: '', loadComponent: () => import('./pages/home/home.page').then(m => m.HomePageComponent) },
	{ path: 'admin/login', loadComponent: () => import('./pages/admin/admin-login.page').then(m => m.AdminLoginPageComponent) },
	{ path: 'admin/:pageKey', canActivate: [adminGuard], loadComponent: () => import('./pages/admin/admin-dashboard.page').then(m => m.AdminDashboardPageComponent) },
	{ path: 'admin', canActivate: [adminGuard], loadComponent: () => import('./pages/admin/admin-dashboard.page').then(m => m.AdminDashboardPageComponent) },
	{ path: 'photos-2025', loadComponent: () => import('./pages/photos-2025/photos-2025.page').then(m => m.Photos2025PageComponent) },
	{ path: 'faq', loadComponent: () => import('./pages/faq/faq.page').then(m => m.FaqPageComponent) },
	{ path: 'contact', redirectTo: 'social', pathMatch: 'full' },
	{ path: 'feedback', loadComponent: () => import('./pages/feedback/feedback.page').then(m => m.FeedbackPageComponent) },
	{ path: 'news/equation', loadComponent: () => import('./pages/news-equation/news-equation.page').then(m => m.NewsEquationPageComponent) },
	{ path: 'news/app', redirectTo: 'news/equation', pathMatch: 'full' },
	{ path: 'news/detail/:id', loadComponent: () => import('./pages/news-detail/news-detail.page').then(m => m.NewsDetailPageComponent) },
	{ path: 'success-stories/:id', loadComponent: () => import('./pages/success-story-detail/success-story-detail.page').then(m => m.SuccessStoryDetailPageComponent) },
	{ path: 'success-stories', loadComponent: () => import('./pages/success-stories/success-stories.page').then(m => m.SuccessStoriesPageComponent) },
	{ path: 'subscription-details', redirectTo: 'subscription-engineering-ar', pathMatch: 'full' },
	{ path: 'subscription-ab-reviews', redirectTo: 'subscription-engineering-ar', pathMatch: 'full' },
	{ path: 'subscription-engineer', redirectTo: 'subscription-engineering-ar', pathMatch: 'full' },
	{ path: 'subscription-computers', redirectTo: 'subscription-computers-ar', pathMatch: 'full' },
	{ path: 'subscription-engineering-ar', loadComponent: () => import('./pages/subscription-ab-reviews/subscription-ab-reviews.page').then(m => m.SubscriptionAbReviewsPageComponent) },
	{ path: 'subscription-computers-ar', loadComponent: () => import('./pages/subscription-ab-reviews/subscription-ab-reviews.page').then(m => m.SubscriptionAbReviewsPageComponent) },
	{ path: 'subscription-engineering-en', loadComponent: () => import('./pages/subscription-ab-reviews/subscription-ab-reviews.page').then(m => m.SubscriptionAbReviewsPageComponent) },
	{ path: 'subscription-computers-en', loadComponent: () => import('./pages/subscription-ab-reviews/subscription-ab-reviews.page').then(m => m.SubscriptionAbReviewsPageComponent) },
	{ path: 'success-story', loadComponent: () => import('./pages/social/social.page').then(m => m.SocialPageComponent) },
	{ path: 'social', redirectTo: 'success-story', pathMatch: 'full' },
	{ path: 'engineers', redirectTo: 'engineers-ar', pathMatch: 'full' },
	{ path: 'engineers-ar', data: { language: 'ar' }, loadComponent: () => import('./pages/engineers/engineers.page').then(m => m.EngineersPageComponent) },
	{ path: 'engineers-en', data: { language: 'en' }, loadComponent: () => import('./pages/engineers/engineers.page').then(m => m.EngineersPageComponent) },
	{ path: 'teacher/:id', loadComponent: () => import('./pages/teacher-details/teacher-details.page').then(m => m.TeacherDetailsPageComponent) },
	{ path: 'requirements', loadComponent: () => import('./pages/requirements/requirements.page').then(m => m.RequirementsPageComponent) },
	{ path: 'schools', loadComponent: () => import('./pages/schools/schools.page').then(m => m.SchoolsPageComponent) },
	{ path: 'batch-2027', loadComponent: () => import('./pages/batch-2027/batch-2027.page').then(m => m.Batch2027PageComponent) },
	{ path: '**', redirectTo: '' },
];
